### ISSUE TITLE
Label and validation for foreing key

### ISSUE THREAD

**Issue by salvacnj** [viewflow/django-material#493] opened 2020-12-20 05:00 UTC
Hello, 

There is an error with foreing key selector labels, they doesn't appear.

![imagen](https://user-images.githubusercontent.com/36660968/102705451-63115d80-4288-11eb-8d5f-051c1af3d7d2.png)

I've found a temporary aesthetic solution, place then with the Fieldset, but it would be nice to solve it. 

![imagen](https://user-images.githubusercontent.com/36660968/102705454-6efd1f80-4288-11eb-8946-8fe0b6390971.png)

Validation for empty field are neither appearing for empty foreing key, and it confuse user when form submition. I attach and example of normal field and a foreing key (wich should have validation).

![imagen](https://user-images.githubusercontent.com/36660968/102705508-0bbfbd00-4289-11eb-9140-7f88cbf4b597.png)

Thank you and regards,
Salva.

**Comment by kmmbvnr** [comment] 2020-12-20 08:51
Can you reproduces it with the demo?

Here is the Country that has the Fk to Continent, and there it seems everything fine with the label - http://demo.viewflow.io/integration/country/121/change/

![CRUD-sample-Viewflow-Demo](https://user-images.githubusercontent.com/282529/102709242-c0320100-42d2-11eb-98f6-b1eabb9f042e.png)

**Comment by salvacnj** [comment] 2020-12-20 14:28
I think the problems came from the add/edit small button wich are on the input.

I'm thinking is could be because I'm using a third app [django-material-admin](https://github.com/MaistrenkoAnton/django-material-admin) for admin panel customization. I override _admin/change_form.html_ template to combine django-material forms with django-material-admin forms (wich display correctly the forms as Is showed in the attached imagen). 

`{% block field_sets %}
	{% if adminform.form.layout %}
		{% form form=adminform.form %}{% endform %}
	{% else %}
		{% for fieldset in adminform %}
			{% include "admin/includes/fieldset.html" %}
		{% endfor %}
	{% endif %}
{% endblock %} `

![django-material-admin fk](https://user-images.githubusercontent.com/36660968/102715579-b7dbc500-42d6-11eb-85a8-46967dbb0387.png)

Is there anyway to directly customize django admin with your app (django-material)?

Thank you and regards,
Salva.

**Comment by kmmbvnr** [comment] 2020-12-20 14:48
django-material has no support for the django admin. There is no plan to add it, since it opens a way to huge amount of possible issues.

i'm closing this, since it looks that the issue related to the django-material-admin  itself.

**Closed by kmmbvnr** 2020-12-20 14:48 UTC
