### ISSUE TITLE
Constraint errors not shown on admin.StackedInline/admin.TabularInline

### ISSUE THREAD

**Issue by fre-sch** [viewflow/django-material#284] opened 2017-05-30 07:56 UTC
Using versions:
```
Python==3.6.1
Django==1.11.1
django-material==0.13.1
```

Model:
```python
class Goal(models.Model):
      title = models.CharField(max_length=255)


class GoalSolution(models.Model):

    class Meta:
        unique_together = (
            ("goal", "creator"),
        )

    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    image = models.ImageField()
```

InlineAdmin:
```python
class GoalSolutionInlineAdmin(admin.TabularInline):
    model = GoalSolution
    extra = 1

```

ModelAdmin:
```python
class GoalAdmin(admin.ModelAdmin):
    inlines = (GoalSolutionInlineAdmin, )
```

After creating the first `GoalSolution` creating another for the same `User` the default theme shows the constraint error above the row: `Goal solution with this Goal and Creator already exists.`

![base-theme-constraint-error](https://cloud.githubusercontent.com/assets/282692/26573264/53d3b1ae-451d-11e7-89ee-18b3a31bf8b3.PNG)

Material Admin theme doesn't display the constraint error message.

![material-theme-constraint-error](https://cloud.githubusercontent.com/assets/282692/26573460/1d00150e-451e-11e7-8245-a43c2a988269.PNG)

**Comment by kmmbvnr** [comment] 2017-05-30 08:24
Mm, strange, it should be fixed in #177 But i didn't check with latest django

**Comment by madEng84** [comment] 2017-07-14 16:11
Any news on this?

**Comment by tomaszgy** [comment] 2017-08-31 15:27
Same here :(

**Comment by tomaszgy** [comment] 2017-08-31 16:08
@fre-sch Do you remember which db did you use?

**Comment by madEng84** [comment] 2017-09-01 00:16
In my case "mysql"

**Comment by fre-sch** [comment] 2017-09-01 04:56
@tomaszgy sqlite3

**Comment by tomaszgy** [comment] 2017-09-05 14:01
We used sqlite3 as well, which doesn't support `unique_together` constraint (the constraint is instead assured by Django Admin according to what I've read on [StackOverflow](https://stackoverflow.com/a/16159180)). Because of that I thought that maybe errors caused by the violation of `unique_together` constraint get to regular `errors` rather than to `non_form_errors` (as they're not checked on db level but on the forms level, thus being rather form errors).
This is not the case when one uses Django Admin panel - it displays the _unique_together constraint errors_ reading from `non_form_errors` method.
Although when one turns Material Admin on, these errors disappear from `non_form_errors` and get to regular `errors` (as I figured out playing with Material's _tabular.html_ template). I have no clue why it happens - @kmmbvnr, do you have any idea?

**Closed** 2017-10-26 08:54 UTC
Labels: admin, bug
