### ISSUE TITLE
Multple Inlines in Admin  page

### ISSUE THREAD

**Issue by TheSundar** [viewflow/django-material#128] opened 2016-06-14 18:44 UTC
Can we have multiple Tablur,Stacked inlines in single admin page

**Comment by kmmbvnr** [comment] 2016-06-15 00:34
Did you try that? It should works

**Comment by kmmbvnr** [comment] 2016-06-15 00:44
I'm closing thia since it's not a bug. Feel free to  reopen if you found issues with multiple inlines on the same page.

**Closed by kmmbvnr** 2016-06-15 00:44 UTC
Labels: admin, question

**Comment by TheSundar** [comment] 2016-06-15 11:03
Thanks for reply,
Yesterday it showed me InlineFormfeildset does not have model object

but today it worked like a charm ! 

Excellent Work ..
