### ISSUE TITLE
admin.TabularInline doesn't show anything

### ISSUE THREAD

**Issue by vemacs** [viewflow/django-material#11] opened 2015-04-21 23:09 UTC
The inline shows on Django default and Grappelli, however, the entire section is empty on django-material

**Comment by kmmbvnr** [comment] 2015-04-22 10:01
Yep, formsets is not supported yet

**Comment by kmmbvnr** [comment] 2015-05-05 11:56
duplicate of  #1

**Closed by kmmbvnr** 2015-05-05 11:56 UTC
